test_user:
    resource: "@TESTUserBundle/Resources/config/routing.yml"
    prefix:   /

test_plateform:
    resource: "@TESTPlateformBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

root:
    pattern:    /
    defaults: 
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /plateform
        permanent: true


login:
    pattern:   /login
    defaults: { _controller: FOSUserBundle:Security:login }

login_check:
    pattern:   /login_check
    defaults: { _controller: FOSUserBundle:Security:check }

logout:
    pattern:   /logout
    defaults: { _controller: FOSUserBundle:Security:logout }

fos_user_security:
     resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
     resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
     prefix: /profile

fos_user_register:
     resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
     prefix: /register

fos_user_resetting:
     resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
     prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
